name: Hasura CI/CD

on:
  # Triggers the workflow on push or pull request events but only for the main, stage branch
  push:
    branches: [ main, stage ]

jobs:
  prod_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      HASURA_ENDPOINT: https://graphql.brewbean.io
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Hasura CI/CD
        uses: GavinRay97/hasura-ci-cd-action@v1.3
        with:
          HASURA_ENDPOINT: HASURA_ENDPOINT
          HASURA_ADMIN_SECRET: ${{ secrets.PROD_HASURA_ADMIN_SECRET }}
          HASURA_MIGRATIONS_ENABLED: true
  
  stage_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    env:
      HASURA_ENDPOINT: https://staging-graphql.brewbean.io
    steps:
      - uses: actions/checkout@v2
      - name: Hasura CI/CD
        uses: GavinRay97/hasura-ci-cd-action@v1.3
        with:
          HASURA_ENDPOINT: HASURA_ENDPOINT
          HASURA_ADMIN_SECRET: ${{ secrets.STAGE_HASURA_ADMIN_SECRET }}
          HASURA_MIGRATIONS_ENABLED: true
