name: Backup Stage from Production

on:
  schedule:
    - cron: "0 20 * * 1"
  workflow_dispatch:

env:
  PROD_APP_NAME: gql-brewbean
  STAGE_APP_NAME: staging-gql-brewbean
  ## Makes HEROKU_API_KEY available to CLI config
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Heroku
        run: sudo apt update && sudo apt install heroku

      - name: Get staging DB URL from Heroku
        run: |
          echo "STAGE_DB_URL=$(heroku config --app ${{ env.STAGE_APP_NAME }} | grep "DATABASE_URL" | cut -d":" -f2- | xargs)" >> $GITHUB_ENV
          echo "staging database URL => ${{ env.STAGE_DB_URL }}"

      - name: Get production DB URL from Heroku
        run: |
          echo "PROD_DB_URL=$(heroku config --app ${{ env.PROD_APP_NAME }} | grep "DATABASE_URL" | cut -d":" -f2- | xargs)" >> $GITHUB_ENV
          echo "production database URL => ${{ env.PROD_DB_URL }}"

      - name: Copy DB from Prod to Stage
        run: heroku pg:copy ${{ env.PROD_APP_NAME }}::${{ env.PROD_DB_URL }} ${{ env.STAGE_DB_URL }} --app ${{ env.STAGE_APP_NAME }}
