name: Copy production DB to staging DB

on:
  schedule:
    - cron: "0 20 * * 1"
  workflow_dispatch:

env:
  PROD_APP_NAME: gql-brewbean
  STAGE_APP_NAME: staging-gql-brewbean
  ## Makes HEROKU_API_KEY available to CLI config
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Heroku
        run: sudo apt-get update && sudo apt-get install heroku

      - name: Copy DB from Prod to Stage [DESTRUCTIVE]
        run: heroku pg:copy ${{ env.PROD_APP_NAME }}::DATABASE_URL DATABASE_URL --app ${{ env.STAGE_APP_NAME }} --confirm ${{ env.STAGE_APP_NAME }}
